param(
  [string]$Root = "D:\projects\open-browser"
)

$ErrorActionPreference = "Stop"

$ExportDir = Join-Path $Root "github_export"
$ZipDir = Join-Path $Root "github_export_zips"
$LogsDir = Join-Path $Root "logs"

New-Item -ItemType Directory -Force -Path $ExportDir | Out-Null
New-Item -ItemType Directory -Force -Path $ZipDir | Out-Null
New-Item -ItemType Directory -Force -Path $LogsDir | Out-Null

Write-Host "ExportDir=$ExportDir"
Write-Host "ZipDir=$ZipDir"

$folders = Get-ChildItem -Path $ExportDir -Directory | Sort-Object LastWriteTime -Descending
if (-not $folders -or $folders.Count -eq 0) {
  throw "No export folders found in $ExportDir. Click Export redacted in Open Browser before closing it."
}

$latest = $folders[0]
$exportPath = $latest.FullName
$exportName = $latest.Name
$runId = $exportName -replace "_github_redacted$",""

Write-Host "LatestExport=$exportPath"
Write-Host "RunId=$runId"
Write-Host "--- Export listing before finalize ---"
Get-ChildItem -Path $exportPath -Force | Format-Table Name,Length,LastWriteTime -AutoSize | Out-String | Write-Host

$logsRun = Join-Path $LogsDir ($runId + ".ndjson")
$answer = Join-Path $exportPath "answer.txt"
$messages = Join-Path $exportPath "messages.ndjson"
$redacted = Join-Path $exportPath "run.redacted.ndjson"
$manifest = Join-Path $exportPath "manifest.json"
$readme = Join-Path $exportPath "README_EXPORT.md"
$synthetic = Join-Path $exportPath "synthetic_messages.ndjson"

$runLogStatus = "missing"
$runLogBytes = 0
if (Test-Path $logsRun) {
  $runLogBytes = (Get-Item $logsRun).Length
  if ($runLogBytes -gt 0) { $runLogStatus = "present" } else { $runLogStatus = "empty" }
}

if ((-not (Test-Path $redacted)) -or ((Get-Item $redacted).Length -eq 0)) {
  $noticeObj = [ordered]@{
    tsUtc = (Get-Date).ToUniversalTime().ToString("o")
    source = "export_finalize"
    eventType = "export_notice"
    status = "source_run_log_$runLogStatus"
    runId = $runId
    message = "run.redacted.ndjson was empty or missing; generated diagnostic notice instead of silently exporting an empty file."
    data = [ordered]@{
      sourceRunLog = $logsRun
      sourceRunLogBytes = $runLogBytes
      note = "No raw stream is included in GitHub export."
    }
  }
  $noticeObj | ConvertTo-Json -Compress -Depth 8 | Set-Content -Path $redacted -Encoding UTF8
}

$readmeLines = @(
  "# Open Browser redacted export",
  "",
  "This folder is a GitHub-safe export package for a single Open Browser diagnostic run.",
  "",
  "Files:",
  "",
  "1. answer.txt: reconstructed assistant messages outside the ChatGPT DOM.",
  "2. messages.ndjson: structured assistant message frames.",
  "3. run.redacted.ndjson: redacted diagnostic run log or export notice.",
  "4. manifest.json: export metadata and file sizes.",
  "5. synthetic_messages.ndjson: synthetic sample message-frame log.",
  "",
  "Safety:",
  "",
  "This export is intended not to include raw stream chunks, cookies, bearer tokens, session tokens, sentinel/proof/verify values, or WebView profile data.",
  "",
  "If the source run log was empty or unavailable, run.redacted.ndjson contains an export_notice record instead."
)
Set-Content -Path $readme -Value $readmeLines -Encoding UTF8

if (-not (Test-Path $synthetic)) {
  $sample = @(
    '{"messageId":"synthetic-message-1","startedAt":"2026-05-09T12:00:00.0000000Z","endedAt":"2026-05-09T12:00:01.0000000Z","role":"assistant","channel":"final","chars":31,"deltaCount":3,"status":"complete","endReason":"last_token","sawLastToken":true}',
    '{"messageId":"synthetic-message-2","startedAt":"2026-05-09T12:00:05.0000000Z","endedAt":"2026-05-09T12:00:06.0000000Z","role":"assistant","channel":"final","chars":74,"deltaCount":5,"status":"complete","endReason":"last_token","sawLastToken":true}'
  )
  Set-Content -Path $synthetic -Value $sample -Encoding UTF8
}

function FileInfoOrNull($path) {
  if (Test-Path $path) {
    $item = Get-Item $path
    return [ordered]@{ exists = $true; bytes = $item.Length; lastWriteTimeUtc = $item.LastWriteTimeUtc.ToString("o") }
  }
  return [ordered]@{ exists = $false; bytes = 0; lastWriteTimeUtc = $null }
}

$manifestObj = [ordered]@{
  exportVersion = "v0.01.0-alpha.10"
  generatedAtUtc = (Get-Date).ToUniversalTime().ToString("o")
  root = $Root
  exportFolder = $exportPath
  runId = $runId
  runLogStatus = $runLogStatus
  sourceRunLog = $logsRun
  sourceRunLogBytes = $runLogBytes
  files = [ordered]@{
    answer = FileInfoOrNull $answer
    messages = FileInfoOrNull $messages
    redactedRun = FileInfoOrNull $redacted
    readme = FileInfoOrNull $readme
    syntheticMessages = FileInfoOrNull $synthetic
  }
  safety = [ordered]@{
    includesRawStream = $false
    includesWebViewProfile = $false
    includesCookies = $false
    includesAuthorizationHeaders = $false
    note = "Generated by alpha.10 automation. Review before public GitHub publication."
  }
}
$manifestObj | ConvertTo-Json -Depth 8 | Set-Content -Path $manifest -Encoding UTF8

Write-Host "--- Export listing after finalize ---"
Get-ChildItem -Path $exportPath -Force | Format-Table Name,Length,LastWriteTime -AutoSize | Out-String | Write-Host

$zipPath = Join-Path $ZipDir ($exportName + ".zip")
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Compress-Archive -Path (Join-Path $exportPath "*") -DestinationPath $zipPath -Force
if (-not (Test-Path $zipPath)) { throw "ZIP was not created: $zipPath" }
$zipItem = Get-Item $zipPath
if ($zipItem.Length -le 0) { throw "ZIP has zero bytes: $zipPath" }

Write-Host "ZIP=$zipPath"
Write-Host "ZIP_BYTES=$($zipItem.Length)"
Write-Host "--- ZIP dir listing ---"
Get-ChildItem -Path $ZipDir -Force | Sort-Object LastWriteTime -Descending | Format-Table Name,Length,LastWriteTime -AutoSize | Out-String | Write-Host
Start-Process explorer.exe "/select,`"$zipPath`""
